In [1]:
import cv2
import numpy as np
import os
from skimage.segmentation import slic
from skimage.segmentation import mark_boundaries
from skimage.util import img_as_float
from skimage import io
from matplotlib import pyplot as plt
import matplotlib.path as mplPath
import xml.etree.ElementTree as ET
import Util

In [2]:
folderPageImages = 'parzivalDataset'; 
folderGroundThruth = 'groundTruth'
ximg_train = []; ximg_test = []; ximg_validation = [];
ximg_train_superpixels = [];
ximgresized_train = []; ximgresized_test = []; ximgresized_validation = [];
xgt_train = []; xgt_test = []; xgt_validation = [];
x_train = []; y_train = []
x_test = []; y_test = []
x_va = []; y_va = []
x = []; y = []


#### Leyendo las imágenes de los documentos y sus respectivos archivos XML que contienen los segmentos (ground truth) como coordenadas de polígonos


In [3]:
ximg_train,      xgt_train      = Util.readPageImagesAndGroundTruth(folderPageImages, folderGroundThruth, 'train')     
ximg_test,       xgt_test       = Util.readPageImagesAndGroundTruth(folderPageImages, folderGroundThruth, 'test')
ximg_validation, xgt_validation = Util.readPageImagesAndGroundTruth(folderPageImages, folderGroundThruth, 'validation')


####  Reduciendo las imágenes a escala

In [4]:
ximgresized_train = Util.resizeImages(ximg_train, 2**-3)
ximgresized_test = Util.resizeImages(ximg_train, 2**-3)
ximgresized_validation = Util.resizeImages(ximg_train, 2**-3)

index 7 to samples

#### Segmentando las imágenes en super píxeles, usando la técnica de SLIC

In [5]:
ximg_train_superpixels = Util.segmentImageInSuperpixels(ximg_train, 3000)

In [19]:
image = ximg_train[7]
imgSegmented = mark_boundaries(image, ximg_train_superpixels[7], color=(1, 0, 0), outline_color=None, mode='outer', background_label=0)
print(imgSegmented)
print(image)
print(ximg_train_superpixels)
#Util.subplot(['imagen', 'imagen segmentada'], [image, imgSegmented], 2, 1, 20)
fig, ax = plt.subplots(figsize=(20,20))
plt.imshow(cv2.cvtColor(imgSegmented, cv2.COLOR_BGR2RGB))
plt.xticks([]),
plt.yticks([])
plt.show()

[[[ 0.12941176  0.1254902   0.20392157]
  [ 0.10980392  0.11372549  0.19215686]
  [ 0.10588235  0.12156863  0.19607843]
  ..., 
  [ 0.0627451   0.05490196  0.05098039]
  [ 0.0627451   0.06666667  0.05882353]
  [ 0.06666667  0.07058824  0.0627451 ]]

 [[ 0.2         0.21568627  0.30980392]
  [ 0.18823529  0.20392157  0.29803922]
  [ 0.18431373  0.20784314  0.29803922]
  ..., 
  [ 0.04313725  0.03529412  0.03137255]
  [ 0.03529412  0.03921569  0.03137255]
  [ 0.03137255  0.03529412  0.02745098]]

 [[ 0.23921569  0.2745098   0.40392157]
  [ 0.23137255  0.2745098   0.4       ]
  [ 0.23137255  0.28235294  0.40784314]
  ..., 
  [ 0.04705882  0.03921569  0.03529412]
  [ 0.04313725  0.04705882  0.03921569]
  [ 0.04705882  0.05098039  0.04313725]]

 ..., 
 [[ 0.14901961  0.2         0.38039216]
  [ 0.15686275  0.20784314  0.38823529]
  [ 0.17254902  0.21176471  0.39607843]
  ..., 
  [ 0.03921569  0.          0.        ]
  [ 0.03529412  0.          0.        ]
  [ 0.03529412  0.          0.     

error: D:\Build\OpenCV\opencv-3.2.0\modules\imgproc\src\color.cpp:9710: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor
